### ISSUE TITLE
Fix issue with writing to flash

### ISSUE THREAD

**Issue by bjorfoss** [Prosjekt2-09arduino/STK500-Android#31]

**Comment by bjorfoss** [comment]
programPage writes data, but not in an expected way
programFlashMemory doesn't write at all, or at least doesn't receive confirmation from the Arduino

**Comment by LaStrada** [comment]
The change of loadAddress fixed #31. The address have to be loaded each time and the address that has to be load is the address divided on 2.
Example: Load address 128 to write from byte address 256.
